# Generated by Django 5.2.10 on 2026-01-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='id_supplier',
            field=models.CharField(max_length=50, unique=True, verbose_name='Supplier ID'),
        ),
    ]
