# Generated by Django 5.2.10 on 2026-02-18 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_country_currency'),
        ('materials', '0004_material_material_type_material_status_material_unit'),
        ('suppliers', '0002_alter_suppliers_id_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('symbol', models.CharField(blank=True, max_length=100, verbose_name='Symbol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Status',
                'verbose_name_plural': 'Order Statuses',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_purchase_order', models.CharField(max_length=10, verbose_name='ID Purchase Order')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('estimated_delivery_date', models.DateField(verbose_name='Estimated delivery date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_supplier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='suppliers.suppliers', verbose_name='Supplier')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='purchases.orderstatus', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
            },
        ),
        migrations.CreateModel(
            name='LinesPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_purchase_order_line', models.CharField(max_length=10, verbose_name='ID Purchase Order Line')),
                ('position', models.IntegerField(default=1, verbose_name='Position')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('price', models.FloatField(verbose_name='Price')),
                ('received_quantity', models.IntegerField(verbose_name='Received Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('currency_supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Currency')),
                ('id_material', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='id_material_1', to='materials.material', verbose_name='Material')),
                ('unit_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.unit', verbose_name='Unit')),
                ('id_purchase_order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='purchases.purchaseorder', verbose_name='Purchase Order')),
            ],
            options={
                'verbose_name': 'Lines Purchase Order',
                'verbose_name_plural': 'Lines Purchase Orders',
            },
        ),
    ]
