# Generated by Django 5.2.10 on 2026-02-18 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_country_currency'),
        ('materials', '0004_material_material_type_material_status_material_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationInventory',
            fields=[
                ('id_location', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Location ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('main_location', models.BooleanField(default=False, verbose_name='Main Location')),
                ('location', models.TextField(blank=True, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Inventory Location',
                'verbose_name_plural': 'Inventory Locations',
            },
        ),
        migrations.CreateModel(
            name='MovementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movement Type',
                'verbose_name_plural': 'Movement Types',
            },
        ),
        migrations.CreateModel(
            name='InventoryMovements',
            fields=[
                ('id_inventory_movement', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Inventory Movement ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material', verbose_name='Material ID')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.unit', verbose_name='Unit Type')),
                ('id_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.locationinventory', verbose_name='Location ID')),
                ('movement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.movementtype', verbose_name='Movement ID')),
            ],
            options={
                'verbose_name': 'Inventory Movement',
                'verbose_name_plural': 'Inventory Movements',
            },
        ),
    ]
