# Generated by Django 5.2.10 on 2026-02-18 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_country_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id_account_group', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Account group ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('code_prefix', models.CharField(max_length=10, verbose_name='Code prefix')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Group',
                'verbose_name_plural': 'Account Groups',
            },
        ),
        migrations.CreateModel(
            name='AccountNature',
            fields=[
                ('id_account_nature', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Account nature ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
                ('effect_on_balance', models.TextField(verbose_name='Effect on balance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Nature',
                'verbose_name_plural': 'Account Natures',
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id_account_type', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Account type ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Type',
                'verbose_name_plural': 'Account Types',
            },
        ),
        migrations.CreateModel(
            name='AccountAccount',
            fields=[
                ('id_account', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Account ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_control_account', models.BooleanField(default=False, verbose_name='Is Control Account')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.country', verbose_name='Country ID')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Currency ID')),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountaccount', verbose_name='Parent Account')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.status', verbose_name='Status')),
                ('account_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.accountgroup', verbose_name='Account Group')),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.accountnature', verbose_name='Account Nature')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.accounttype', verbose_name='Account Type')),
            ],
            options={
                'verbose_name': 'Account ',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
