# Generated by Django 5.2.10 on 2026-02-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountgroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
