# Generated by Django 5.2.10 on 2026-02-18 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_accountgroup_name'),
        ('core', '0002_country_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountaccount',
            name='currency_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Currency ID'),
        ),
    ]
